# Use an official Python runtime as the base image
FROM amd64/python:3.9-buster as project_env

# Set the working directory in the container
WORKDIR /app

# Install dependencies
COPY updater-requirements.txt updater-requirements.txt
RUN pip install --upgrade pip setuptools \
    && pip install --timeout=360 --no-cache-dir -r updater-requirements.txt

FROM project_env

COPY update_app.py app_config.py app_utils.py /app/

# Set the entrypoint command
ENTRYPOINT ["sh", "-c", "while true; sleep 60; do python -u /app/update_app.py; done"]