# Use an official Python runtime as the base image
FROM amd64/python:3.9-buster as project_env

# Set the working directory in the container
WORKDIR /app

# Install dependencies
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip setuptools \
    && pip install --timeout=360 --no-cache-dir -r requirements.txt

FROM project_env

COPY train_models.py app_config.py /app/

# Set the entrypoint command
ENTRYPOINT ["sh", "-c", "python -u /app/train_models.py && while true; do sleep 3600; python -u /app/train_models.py; done"]